import esbuild from "esbuild";
import path from "path";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { fileURLToPath } from "url";

// Absolute path to this config's own directory (the plugin root), independent of
// the process cwd, so the dedup aliases below always target the PLUGIN's own
// node_modules.
const pluginRoot = path.dirname(fileURLToPath(import.meta.url));

// Load .env.local if it exists
if (existsSync(".env.local")) {
  const envContent = readFileSync(".env.local", "utf-8");
  for (const line of envContent.split("\n")) {
    const match = line.match(/^([^=]+)=["']?(.+?)["']?$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2];
    }
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Obsidian plugin folder path (set via OBSIDIAN_VAULT env var or .env.local)
const OBSIDIAN_VAULT = process.env.OBSIDIAN_VAULT;
const OBSIDIAN_PLUGIN_PATH =
  OBSIDIAN_VAULT && existsSync(OBSIDIAN_VAULT)
    ? path.join(
        OBSIDIAN_VAULT,
        ".obsidian",
        "plugins",
        "archivist"
      )
    : null;

// Plugin to copy built files to Obsidian plugin folder
const copyToObsidian = {
  name: "copy-to-obsidian",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0 || !OBSIDIAN_PLUGIN_PATH) return;

      if (!existsSync(OBSIDIAN_PLUGIN_PATH)) {
        mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true });
      }

      const files = ["main.js", "manifest.json", "styles.css"];
      for (const file of files) {
        if (existsSync(file)) {
          copyFileSync(file, path.join(OBSIDIAN_PLUGIN_PATH, file));
          console.log(`Copied ${file} to Obsidian plugin folder`);
        }
      }

    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["packages/obsidian/src/main.ts"],
  bundle: true,
  plugins: [copyToObsidian],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    ...builtins.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  // Dedup shared runtime deps to the plugin's single node_modules copy. The
  // extracted @archivist/{dnd5e,core} siblings are consumed via symlink; esbuild
  // resolves their real path and would otherwise bundle each sibling's OWN
  // node_modules/{zod,js-yaml} as a duplicate now that npm-workspace hoisting no
  // longer dedupes them. All three repos declare compatible ranges (zod ^4.3.6,
  // js-yaml ^4.1.0), so a single bundled copy matches pre-extraction behaviour.
  alias: {
    zod: path.resolve(pluginRoot, "node_modules/zod"),
    "js-yaml": path.resolve(pluginRoot, "node_modules/js-yaml"),
  },
  loader: {
    ".md": "text",
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
